name: test
channels:
  - defaults
dependencies:
  - python=3.9
  - six=1.16.0
  - matplotlib=3.8.4
  - numpy=1.26.4
  - pillow=10.4.0
  - configobj=5.0.6
  - black
  - flake8
  - pip
  - pip:
    - vtk==9.3.*
    - mayavi==4.8.*
    - types-pillow==10.2.*
